### ISSUE TITLE
Is there any reason for ref-struct-di not being using ref-array-di instead of ref-array?

### ISSUE THREAD

**Issue by viniciusls** [node-ffi-napi/ref-struct-di#15]
Hi,

I'm facing some issues on my Node project using IBM MQ node module (and it's C libraries on MQ Client) and this module uses `ffi-napi`, `ref-array-di`, `ref-napi` and `ref-struct-di`. The issue I'm facing is about `corrupted double-linked list` and `result.second` and it looks like both are generating core dump files and failing.
I was trying to fix `result.second` (and possible `corrupted double-linked list`) by using `npm link` as suggested on this issue https://github.com/node-ffi-napi/node-ffi-napi/issues/96 to avoid multiple different references to the same libraries and I've noticed that when I tried `npm link` on `ref-struct-di` it's failing on `node-gyp` because of `ref` library. I've checked and `ref-struct-di` is using `ref-napi` instead of `ref` but it's also using  `ref-array` which uses `ref` instead of `ref-napi` and I wonder why aren't you using `ref-array-di` on `ref-struct-di` instead of using `ref-array` (specially considering that all these projects are maintained by the same team)?
I'm using Node v14.12.0 - and have no option to rollback to version 12 because of business requirements and security reasons (even though version 12 works well with almost no `corrupted double-linked list` - I haven't tried `npm link` these dependencies there because there was no need like on version 14 with those issues).

Thanks in advance,
Vinícius Silva

**Comment by addaleax** [comment]
I think you can feel free to submit a PR that does the update and I’ll merge it. Since all those dependencies here are devDependencies, I figured using any kind of `ref-array` library would be fine, as consumers wouldn’t care.

**Comment by addaleax** [comment]
I think #16 fixed this.
